### PR TITLE
Added an detail to cloudflare custom DNS config

### PR DESCRIPTION
**Pull request by jonathanstiansen**
Just had a small issue with only using cloudflare for DNS, instead of realizing I needed to send all traffic through cloudflare I had the setting set to DNS only and was having certificate issues. One I changed that I was able to move forward. :-)

### CODE REVIEW

**Comment by jonathanstiansen** [comment]
I've now signed the CLA. Not entirely sure why it still says some checks haven't completed.

**Comment by kborchers** [comment]
Hi @jonathanstiansen it looks like you committed your changes with a different account as the commit is attributed to @hobnob-upcase. You'll either need to amend your commit to have the correct user or sign the CLA with the other account.

**Comment by hobnob-upcase** [comment]
@kborchers Sorry about that! Thanks for letting me know, I'll try to fix that somehow.

**Comment by hobnob-upcase** [comment]
Feel free to close this, I'm going to get it done with my other account. :-)

**Comment by kborchers** [comment]
@hobnob-upcase fyi, you could just do something like

`git commit --amend --author="Author Name <email@address.com>"`

using your other account name and email and then force push to your branch and it should update the PR and be all good

**Comment by jonathanstiansen** [comment]
Pull-request updated, HEAD is now 326d90631e22edf0d35a3892021e8f935eb6e2ab

**Comment by jonathanstiansen** [comment]
Done! :-)

**Comment by brianleroux** [comment]
sweet thx!! 💯

**Pull request merged**
