### PR TITLE
typo fixes

### PR DESCRIPTION
**Pull request by pmuellr**
I started by fixing a windows-encoded dash with an ascii dash, but then couldn't
stop myself.  Just fixing the red twiddle underlined typos I noticed.

No idea how to test this, I guess this is an arc app, but I don't have the foo
to try testing locally.

### CODE REVIEW

**Comment by pmuellr** [comment]
what I couldn't not fix:

arc

**Comment by pmuellr** [comment]
Likely the unicode dash could be fixed with the right utf8-esque thang in the `<head>` or char-code attr on `<html>`, but ... might as well do it right.

**Comment by brianleroux** [comment]
sweet thx mang!

**Comment by ryanblock** [comment]
@pmuellr that unicode dash char is my fault -- I dropped in an m-dash forgetting that we have an (open) encoding output issue with API gateway. Current workaround: ascii only (lololol).

**Pull request merged**
